title: PulX
default_lang: fr
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - Transmission
  - Spectacle
  - Performance
  - Actualités
  - 'Projet en avant'
  - Archives
metadata:
  description: 'PulX / Elsa Decaudin & … est une structure installée à Montpellier depuis 2004 qui a conçu et diffusé divers projets artistiques et culturels autour du mouvement.'
summary:
  enabled: true
  format: short
  size: 3000
  delimiter: '==='
blog:
  route: /blog
