title: PulX
default_lang: fr
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - Transmission
  - Création
  - Performance
  - Actualités
  - 'À propos'
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
