title: PulX
default_lang: fr
author:
  name: 'Joe Bloggs'
  email: joe@test.com
taxonomies:
  - Transmission
  - Spectacle
  - Performance
  - Actualit√©s
  - 'Projet en avant'
  - Archives
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 3000
  delimiter: '==='
blog:
  route: /blog
